{"uuid": "77ecc9dc-5367-435e-90d5-9979f199108e", "children": ["83af9bb5-8570-4b4d-b74c-7092342e8d98", "89d56b38-f098-44ae-b16e-3a2573adb59e", "7eab8950-835d-4e1d-9e54-2e3b728480fc", "9e272e6d-6607-47e3-b2c3-e0530b355b78", "cb7d59c9-bc97-4ad1-94fa-542556114f4c", "af5ab555-e4d0-4504-98ec-f8ade524f250", "725a1aaf-828b-4a83-a09b-4416ba38445b", "e081cb2f-20fb-4f31-a30b-58910863a782"], "befores": [{"name": "_xunit_setup_class_fixture_TestDropDownList", "status": "broken", "statusDetails": {"message": "TypeError: unsupported callable\n", "trace": "  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 717, in _call_with_optional_argument\n    func()\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 189, in impl\n    params = func_parameters(func, *a, **kw)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Sprint_6\\.venv\\Lib\\site-packages\\allure_commons\\utils.py\", line 231, in func_parameters\n    arg_spec = inspect.getfullargspec(func)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\kolon\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\inspect.py\", line 1398, in getfullargspec\n    raise TypeError('unsupported callable') from ex\n"}, "start": 1735074544508, "stop": 1735074544508}], "start": 1735074544508, "stop": 1735074545072}